### PR TITLE
🍱add remmina

### PR DESCRIPTION
**Pull request by waelouf**
add [remmina](https://hub.docker.com/r/linuxserver/remmina) png icon

### CODE REVIEW

**Comment by ruanmed** [comment]
Hi @waelouf, the CONTRIBUTING.md of this repo specifies that [Gitmoji](https://gitmoji.dev/) must be used on the commit messages. 
I noticed your commit is not adherent to this guideline, therefore I suggest you please add the corresponding gitmoji.

Also, there's the Remmina application icon SVG file in the project GitLab repository:

- https://gitlab.com/Remmina/Remmina/-/blob/master/data/desktop/scalable/apps/org.remmina.Remmina.svg

**Comment by waelouf** [comment]
Hi @ruanmed, 
Thanks for the update, just renamed the PR to use the proper gitmoji
Also, remmina existed in `svg`, but it was missing from `png`, that's why I created this PR

**Review by walkxcode — CHANGES_REQUESTED** [review]
Hi, as @ruanmed said, please add an SVG version and scale the PNG from that.

**Comment by waelouf** [comment]
@walkxcode , @ruanmed finally got back to this :)
added the svg and updated png as required

**Pull request merged**
