### PR TITLE
Add Icons for Sophos, F5-Networks, Palo-Alto and Flarum

### PR DESCRIPTION
**Pull request by drag0n141**
Source [Wikipedia ](https://wikipedia.org) and [Icons-Icons](https://icon-icons.com/)

### CODE REVIEW

**Review by walkxcode — CHANGES_REQUESTED** [review]
Hey, thanks for your contribution! Please resize the icons to have a height of `512px` as specified in https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md

**Comment by drag0n141** [comment]
Did not find the F5-Networks as SVG.

**Review by walkxcode — CHANGES_REQUESTED** [review]
Hi, SVGs don't really have a "size" so you can add back the SVG for Flarum.

**Comment by drag0n141** [comment]
SVG for Flarum added.

**Pull request merged**
