### PR TITLE
🍱 Adds TeamSpeak

### PR DESCRIPTION
**Pull request by fredodiable**
Added icon for TeamSpeak

### CODE REVIEW

**Review by walkxcode — CHANGES_REQUESTED** [review]
Hi, please add a transparent version and an SVG version.

**Comment by fredodiable** [comment]
> Hi, please add a transparent version and an SVG version.

Hi, changed png icon and added svg icon

**Review by walkxcode — CHANGES_REQUESTED** [review]
Hi, please upload an actual SVG instead of a PNG file inside of an SVG.

**Comment by fredodiable** [comment]
> Hi, please upload an actual SVG instead of a PNG file inside of an SVG.

Yeah, my bad changed the SVG

**Review by walkxcode — CHANGES_REQUESTED** [review]
Have you… Read the contribution guidelines? PLEASE just read them

**Comment by fredodiable** [comment]
Yes I did read the new guidelines (I already contributed here)
Could not find a proper SVG so I ended with a black monocrhome one, ugly but thought this would be OK with rules
I finaly found a good SVG icon now
Just commited, let me know if it's OK
Sorry for the difficulties

**Review by walkxcode — APPROVED** [review]
Hi, yes this is great! :)

**Pull request merged**
