### PR TITLE
🍱 Adds Keyoxide

### PR DESCRIPTION
**Pull request by parrazam**

### CODE REVIEW

**Comment by Ishmaello** [comment]
Add kiyoxide logo as PNG

**Review by Ishmaello — APPROVED** [review]
This is best

**Comment by walkxcode** [comment]
Hello, Dashboard Icons is migrating to a new standard! Please update your pull request to match this. Read the Contributing Guide [here](https://github.com/walkxcode/dashboard-icons/blob/new-standards/CONTRIBUTING.md).

(Please also change the `...-blue` files to `...-alt`)

**Review by walkxcode — CHANGES_REQUESTED** [review]
Hello, Dashboard Icons is migrating to a new standard! Please update your pull request to match this. Read the Contributing Guide [here](https://github.com/walkxcode/dashboard-icons/blob/new-standards/CONTRIBUTING.md).

(Please also change the `-blue` icons to `-alt`)

**Comment by walkxcode** [comment]
> Hello, Dashboard Icons is migrating to a new standard! Please update your pull request to match this. Read the Contributing Guide [here](https://github.com/walkxcode/dashboard-icons/blob/new-standards/CONTRIBUTING.md?rgh-link-date=2023-04-14T17%3A16%3A05Z).
> 
> (Please also change the `-blue` icons to `-alt`)

@parrazam

**Comment by parrazam** [comment]
Sorry for the delay, done!!

**Pull request merged**
