### PR TITLE
🍱 Update Speedtest-Tracker PNG 

### PR DESCRIPTION
**Pull request by ArthurHuyghe**
I updated the  Speedtest-Tracker.png to the new icon from [alexjustesen/speedtest-tracker](https://github.com/alexjustesen/speedtest-tracker/blob/21125195ccdc6549093bbec855a5fccfbfc64d7e/public/img/speedtest-tracker-icon.png).

### CODE REVIEW

**Review by walkxcode — CHANGES_REQUESTED** [review]
Hey, this icon doesn't seem to be actually used anywhere. Are you sure this is the one that is actively being used?

**Comment by quentains** [comment]
I think there is a confusion between two projects.

- https://github.com/henrywhitaker3/Speedtest-Tracker
- https://github.com/alexjustesen/speedtest-tracker/tree/21125195ccdc6549093bbec855a5fccfbfc64d7e

**Comment by ArthurHuyghe** [comment]
I opened a [issue](https://github.com/alexjustesen/speedtest-tracker/issues/1331#issue-2211262742) to ask the maintainer for his plans with this icon and for his opinion on the change.

**Comment by ArthurHuyghe** [comment]
> The rabbit is the icon I'm using in the app and in the docs and making no plans on changing it.
This was the response from @alexjustesen.

**Comment by walkxcode** [comment]
@ArthurHuyghe Thanks for the work! I'll add in the old icon as suggested.

**Pull request merged**
