### PR TITLE
Add Icon for Crafty Controller

### PR DESCRIPTION
**Pull request by Nuhser**
### What has been added

- 512x512 .png logo for Crafty Controller (crafty-controller.png)

### Note
- there were no .svg available

### CODE REVIEW

**Comment by Tinyblargon** [comment]
Their full logo has the the icon in it, I'll look into extracting it somewhere this week to create the an svg logo.
https://gitlab.com/crafty-controller/crafty-4/-/blob/de97cb799ef6496f63b0803a2101b91165946f26/app/frontend/static/assets/images/logo_long.svg

**Comment by walkxcode** [comment]
@Tinyblargon Please do! Thanks 🙂

**Comment by Tinyblargon** [comment]
@walkxcode currently waiting on this PR https://gitlab.com/crafty-controller/crafty-4/-/merge_requests/666

**Comment by walkxcode** [comment]
Merging this one: https://github.com/walkxcode/dashboard-icons/pull/534

**Pull request closed without merging**
