### PR TITLE
Added Openshift and pcloud PNG

### PR DESCRIPTION
**Pull request by erwinmintiens**

### CODE REVIEW

**Review by walkxcode — COMMENTED** [review]
Hi, are you sure none of these icons have an SVG version available?

**Comment by erwinmintiens** [comment]
They could have, but none that I could find.

**Comment by driversti** [comment]
We can find SVGs of both on Wikimedia:
[openshift](https://commons.wikimedia.org/wiki/File:OpenShift-LogoType.svg)
[pcloud](https://commons.wikimedia.org/wiki/File:Pcloud-logo.svg)

**Comment by jaws316** [comment]
sblogo

**Review by walkxcode — CHANGES_REQUESTED** [review]
Hi, would you be able to add the SVG files linked above? Thanks!

**Pull request closed without merging**
