### PR TITLE
please add those icons if possible

### PR DESCRIPTION
**Pull request by IIIdefconIII**
please add those icons if possible

### CODE REVIEW

**Review by walkxcode — CHANGES_REQUESTED** [review]
Hey, I was going to do everything myself, but luckily you made a PR! There are a lot of changes that should be made though, feel free to do these yourself, or if not, tell me and I will happily do them for you :D 

Make `cyberthreatsmap.webp` a PNG file.
Add a PNG version of `hotio.svg`.
Make the `insanelymac.png` icon something close to a 1:1 aspect ratio (E.g. Remove the text)
Change the `netgreat-router` icon to something without a watermark.
Change `ondertitelscc.png` to either `cc.png` or `closed-captions.png` (or both with one copy).
Make a copy of `pirateproxy.png` called `the-pirate-bay.png`.
Change `pirvatebin.svg` to `privatebin.png` and also add a working PNG version.
Remove the `reddit.png/svg` changes.
Add a PNG version of `shelltips.svg`.
Make `ytsdll.png` and `ytsdo.png` a 1:1 aspect ratio.

Make sure all PNG versions of SVG's are at least 100x100px.

**Comment by IIIdefconIII** [comment]
I can try to create them somewhere this week. I'll update the post once their done

**Comment by IIIdefconIII** [comment]
changed cybertheartsmap to kaspersky in png format:
kaspersky

**Comment by IIIdefconIII** [comment]
hotio.png
hotio

**Comment by IIIdefconIII** [comment]
insanelymac
insanelymac

**Comment by IIIdefconIII** [comment]
netgearrouter
netgearrouter

**Comment by IIIdefconIII** [comment]
CC:
cc

**Comment by IIIdefconIII** [comment]
the-pirate-bay.png
the-pirate-bay png

**Comment by IIIdefconIII** [comment]
shelltips

shelltips

**Comment by IIIdefconIII** [comment]
YTS

yts

**Comment by IIIdefconIII** [comment]
did my best, not sire why there is some white at YTS and shelltips do

**Comment by IIIdefconIII** [comment]
> Hey, I was going to do everything myself, but luckily you made a PR! There are a lot of changes that should be made though, feel free to do these yourself, or if not, tell me and I will happily do them for you :D
> 
> Make `cyberthreatsmap.webp` a PNG file. Add a PNG version of `hotio.svg`. Make the `insanelymac.png` icon something close to a 1:1 aspect ratio (E.g. Remove the text) Change the `netgreat-router` icon to something without a watermark. Change `ondertitelscc.png` to either `cc.png` or `closed-captions.png` (or both with one copy). Make a copy of `pirateproxy.png` called `the-pirate-bay.png`. Change `pirvatebin.svg` to `privatebin.png` and also add a working PNG version. Remove the `reddit.png/svg` changes. Add a PNG version of `shelltips.svg`. Make `ytsdll.png` and `ytsdo.png` a 1:1 aspect ratio.
> 
> Make sure all PNG versions of SVG's are at least 100x100px.

i think its ok like this right?

**Comment by IIIdefconIII** [comment]
wud
wud.png whatsuppdocker

**Pull request closed without merging**
