### PR TITLE
🍱 Adds Stump

### PR DESCRIPTION
**Pull request by MatthewGlenn**
Includes the .png for stump in the issue and I created an .svg version as well.
https://github.com/walkxcode/dashboard-icons/issues/733

### CODE REVIEW

**Comment by wwwescape** [comment]
Could you add the alternate version as well?

Ref: #734.

I will then close my PR.

**Comment by MatthewGlenn** [comment]
> Could you add the alternate version as well?
> 
> Ref: #734.
> 
> I will then close my PR.

I added the alt image.

However, I'm not really sure how this project handles alt images. I noticed a couple `-alt.svg` images but no `-alt.png` images. 
@walkxcode could we get some guidance on this in the Contribution Guidelines?

**Comment by wwwescape** [comment]
> > Could you add the alternate version as well?
> > Ref: #734.
> > I will then close my PR.
> 
> I added the alt image.
> 
> However, I'm not really sure how this project handles alt images. I noticed a couple `-alt.svg` images but no `-alt.png` images. @walkxcode could we get some guidance on this in the Contribution Guidelines?

Thanks. I will close my PR.

Regarding the alt, images. I think we still need a PNG and an SVG. This is what I did for [GoDaddy](https://github.com/walkxcode/dashboard-icons/pull/735). However, let @walkxcode confirm.

**Comment by walkxcode** [comment]
Apologies for the delay. Alt versions should always be included for both SVG and PNG files. It’s possible some PNGs went missing after the standards update. I’ve merged the PR for now, but please ensure an SVG is added for the alt version as well!

**Pull request merged**
