### PR TITLE
🍱 Adds Snapcast

### PR DESCRIPTION
**Pull request by apo-mak**
Snapcast:

Synchronous audio player

🍱 added snapcast.png

https://github.com/badaix/snapcast

### CODE REVIEW

**Comment by apo-mak** [comment]
bump

**Comment by apo-mak** [comment]
@walkxcode dose it need anything else to be merged ?

**Comment by apo-mak** [comment]
?

**Comment by apo-mak** [comment]
?

**Review by walkxcode — CHANGES_REQUESTED** [review]
Hi, could you add the current icon as snapcast-alt. And add a cropped version with just the icon as the main version? Thanks! 

You can read more about the guidelines here: https://github.com/walkxcode/dashboard-icons/blob/main/CONTRIBUTING.md

**Comment by apo-mak** [comment]
> alt

Done 😄

**Pull request closed without merging**
